apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the storage capacity as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # Adjust access mode based on your requirements
  nfs:
    path: /srv/nfs/kubedata
    server: 65.0.31.178 
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual  # Optional, specify if using dynamic provisioning

