apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: manual
  nfs:
    server: "15.207.114.182"
    path: "/srv/nfs/kube"

