apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs1
spec:
  accessModes:
    - ReadWriteMany  # Adjust access mode based on your PV
  storageClassName: manual  # Set to the storage class name used by your PV, or leave it empty for manual allocation
  resources:
    requests:
      storage: "500Mi"
