apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs
spec:
  accessModes:
    - ReadWriteMany  # Adjust access mode based on your PV
  storageClassName: manual  # Set to the storage class name used by your PV, or leave it empty for manual allocation
  resources:
    requests:
      storage: 1Gi  # Adjust the requested storage size as needed
