apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: kumarolipi/jenkins-docker:latest
    volumeMounts:
    - name: host-volume  
      mountPath: /usr/share/nginx/html
  volumes:
  - name: host-volume
    persistentVolumeClaim:
      claimName: pvc

