apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myweb
        image: kumarolipi/jenkins-docker:latest
  resources:
    limits:
    memory: "100Mi"
