apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlcm
data:
  my.cnf: |
    [mysqld]
    pid-file = /var/run/mysqld/mysqld.pid
    socket = /var/run/mysqld/mysqld.sock
    port  = 9999
    datadir = /var/lib/mysql
    log_error = /var/log/mysql/error.log
