apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  volumes:
  - name: configmap
    configMap:
      name: configmap
  containers:
  - image: busybox
    name: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
    env:
    volumeMounts:
    - name: configmap
      mountPath: /mydata

