apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb 
spec:
  replicas: 4 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myweb
        image: kumarolipi/jenkins-docker:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: my-app
          mountPath: /usr/share/nginx/html
      volumes:
      - name: my-app
        persistentVolumeClaim:
          claimName: pvc
