apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: myds
  labels:
    app: myweb
spec:
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: nginx:latest
      nodeSelector:
        env: prod

