apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      volumes:  # This is the correct field name
      - name: shared-volume
        emptyDir: {}
      initContainers:
      - name: init-container
        image: kumarolipi/jenkins-docker:latest
      containers:
      - name: main-container
        image: kumarolipi/jenkins-docker:latest
        ports:
        - containerPort: 80
